version: "3"

services: 
  python:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:8888
    command: bash -c "jupyter notebook --port=8888 --no-browser --ip='0.0.0.0' --allow-root"